"use client";
import { useEffect, useState } from "react";

const team=["Emmanuel Juárez","Saúl García","Jessica Juárez","Cynthia Trejo","Guadalupe Dávila","Iván Nicasio","Hazael","Ángel Nava"];
const nav=[["01","Afinidad","afinidad"],["02","Vectores","vectores"],["03","Escenarios","escenarios"],["EN VIVO","Pulso","pulso"],["04","Cierre","cierre"]];
const ideas=["Automatización inteligente","Energía renovable","Certificación internacional","Trabajo colaborativo","Producción distribuida","Diseño nacional","Competencia global","Cambio demográfico"];
const groups=[{name:"Tecnología y manufactura",items:["Automatización inteligente","Producción distribuida","Diseño nacional"],color:"#2e9e6b"},{name:"Entorno y competitividad",items:["Energía renovable","Certificación internacional","Competencia global"],color:"#b8912f"},{name:"Sociedad y trabajo",items:["Trabajo colaborativo","Cambio demográfico"],color:"#c0492e"}];
const worlds=[{name:"Dependencia técnica",x:20,y:22,color:"#c0492e",text:"Tecnología importada y formación principalmente técnica."},{name:"Talento integrado",x:27,y:76,color:"#8a6d2f",text:"Capacidad humana alta, aunque dependiente de tecnología externa."},{name:"Transición incierta",x:52,y:50,color:"#b8912f",text:"Señales contradictorias y capacidades todavía en construcción."},{name:"Innovación parcial",x:74,y:28,color:"#2e9e6b",text:"Mayor autonomía tecnológica, pero con integración humana limitada."},{name:"Futuro deseable",x:82,y:80,color:"#146b49",text:"Desarrollo nacional con habilidades técnicas y sociales integradas."}];
const pollChoices=[["tecnologia","Tecnologías emergentes"],["humanas","Nueva cultura de trabajo"],["sustentabilidad","Energía y sustentabilidad"],["autonomia","Diseño y desarrollo local"],["global","Competitividad global"]];

export default function Home(){
 const [active,setActive]=useState("portada"),[progress,setProgress]=useState(0),[scenario,setScenario]=useState(4),[group,setGroup]=useState(0);
 const [vote,setVote]=useState(""),[results,setResults]=useState<Record<string,number>>({}),[count,setCount]=useState(0),[status,setStatus]=useState("");
 useEffect(()=>{const ss=[...document.querySelectorAll<HTMLElement>("section[id]")];const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:"-42% 0px -48%"});ss.forEach(s=>io.observe(s));const scroll=()=>{const d=document.documentElement;setProgress(d.scrollHeight>d.clientHeight?100*d.scrollTop/(d.scrollHeight-d.clientHeight):0)};addEventListener("scroll",scroll,{passive:true});return()=>{io.disconnect();removeEventListener("scroll",scroll)}},[]);
 useEffect(()=>{let live=true;const load=()=>fetch("/api/votes",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(live&&d.totals){setResults(d.totals);setCount(d.count)}}).catch(()=>{});load();const t=setInterval(load,3000);setVote(localStorage.getItem("radar-vote")||"");return()=>{live=false;clearInterval(t)}},[]);
 async function submitVote(choice:string){let voterId=localStorage.getItem("radar-voter-id");if(!voterId){voterId=crypto.randomUUID();localStorage.setItem("radar-voter-id",voterId)}setStatus("Enviando…");const r=await fetch("/api/votes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({voterId,choice})});if(r.ok){setVote(choice);localStorage.setItem("radar-vote",choice);setStatus("¡Voto registrado!")}else setStatus("Intenta nuevamente.")}
 return <main>
  <header className="nav"><div className="nav-inner"><a href="#portada" className="logo"><b>R</b><span>RADAR <i>2030</i></span></a><nav>{nav.map(([n,l,id])=><a className={active===id?"on":""} href={`#${id}`} key={id}>{n} · {l}</a>)}</nav></div><div className="bar"><i style={{width:`${progress}%`}}/></div></header>
  <section id="portada" className="cover wrap"><div className="hero-radar" aria-hidden="true"><i/><i/><i/><b/></div><div className="pill"><i/>Equipo 02 · Metodología</div><h1>¿Cómo se construye<br/>un futuro <em>posible?</em></h1><p className="subtitle">Ingeniería Industrial en México 2030 — del pensamiento colectivo a una matriz de escenarios.</p><div className="method-route"><span><b>01</b>Grupos de afinidad</span><i>→</i><span><b>02</b>Vectores</span><i>→</i><span><b>03</b>Escenarios futuros</span></div><div className="facts"><article><small>Universidad</small><b>La Salle Bajío</b><span>Facultad de Ingenierías y Tecnologías</span></article><article><small>Exposición</small><b>Miércoles 19 · Ago 2026</b><span>Equipo #2 · 15 minutos</span></article><article><small>Método base</small><b>Global Business Network</b><span>Planeación por escenarios · Pierre Wack</span></article></div><div className="team"><small>EQUIPO #2</small><div>{team.map(p=><span key={p}>{p}</span>)}</div></div></section>
  <section className="section pale" id="afinidad"><div className="wrap"><Title n="01" title="Identificación de grupos de afinidad" text="El proceso comienza abriendo la conversación: muchas señales individuales se convierten en patrones colectivos."/><div className="question"><small>PREGUNTA DETONADORA</small><p>¿Cuáles son las fuerzas ambientales y los factores cruciales que determinarán el futuro de la ingeniería industrial en 2030?</p></div><div className="idea-flow"><div className="idea-cloud">{ideas.map((x,i)=><button className={groups[group].items.includes(x)?"on":""} onClick={()=>setGroup(groups.findIndex(g=>g.items.includes(x)))} key={x}>{x}</button>)}</div><div className="flow-arrow">→</div><article className="group-card" style={{borderColor:groups[group].color}}><small>GRUPO DE AFINIDAD</small><h3>{groups[group].name}</h3>{groups[group].items.map(x=><span key={x}>+ {x}</span>)}</article></div><div className="rules"><b>REGLAS DEL LABORATORIO DE IDEAS</b><span>Sin verbos</span><span>Explícitas</span><span>Máximo 10 palabras</span><span>Reveladoras</span></div><p className="citation">(Asociación Nacional de Facultades y Escuelas de Ingeniería [ANFEI], 2016)</p></div></section>
  <section className="section dark" id="vectores"><div className="wrap"><Title n="02" title="Determinación de vectores" text="Los grupos se sintetizan en ejes de incertidumbre. Al cruzarlos aparece un mapa de futuros, no una predicción única." inverse/><div className="vector-explain"><article><small>¿QUÉ ES UN VECTOR?</small><h3>Una tensión que puede moverse entre dos extremos.</h3><p>Debe representar una disrupción tecnológica, geopolítica o sociocultural, o una tendencia que esté consolidándose.</p></article><div className="vector-demo"><label><span>Tecnología importada</span><i/><span>Desarrollo nacional</span></label><label><span>Sólo orientación técnica</span><i/><span>Habilidades integradas</span></label><label><span>Gran empresa</span><i/><span>Actividad diversificada</span></label></div></div><aside className="vector-formula"><span>GRUPOS DE AFINIDAD</span><b>→</b><span>SÍNTESIS</span><b>→</b><span>VECTORES</span><b>→</b><span>MATRIZ</span></aside></div></section>
  <section className="section" id="escenarios"><div className="wrap"><Title n="03" title="Identificación de escenarios futuros" text="Cada combinación de vectores se convierte en un mundo coherente, recibe un nombre breve y después puede desarrollarse como narrativa."/><div className="scenario-grid"><div className="matrix light-matrix"><label className="top">Habilidades humanas integradas</label><label className="bottom">Sólo orientación técnica</label><label className="left">Tecnología importada</label><label className="right">Desarrollo nacional</label><div className="axis v"/><div className="axis h"/>{worlds.map((w,i)=><button aria-label={w.name} className={scenario===i?"selected":""} onClick={()=>setScenario(i)} key={w.name} style={{left:`${w.x}%`,bottom:`${w.y}%`,background:w.color}}>{i+1}</button>)}</div><article className="scenario-card bordered"><header><i style={{background:worlds[scenario].color}}>{scenario+1}</i><h3>{worlds[scenario].name}</h3></header><b>COMBINACIÓN DE VECTORES</b><p>{worlds[scenario].text}</p><aside><strong>Regla del nombre</strong> Máximo 6 palabras, fácil de identificar y recordar.</aside><small>Selecciona otro punto de la matriz</small></article></div><div className="three-criteria"><article><b>1</b><h3>Coherente</h3><p>Sus condiciones no se contradicen.</p></article><article><b>2</b><h3>Revelador</h3><p>Muestra riesgos u oportunidades.</p></article><article><b>3</b><h3>Memorable</h3><p>Tiene un nombre con sentido narrativo.</p></article></div></div></section>
  <section className="section pale" id="pulso"><div className="wrap"><Title n="EN VIVO" title="Laboratorio de ideas del salón" text="Replicamos una parte del método: cada respuesta individual alimenta una señal colectiva."/><div className="pulse-head"><h3>¿Qué fuerza transformará más<br/>la profesión hacia 2030?</h3><div><i/><b>{count}</b><span>participaciones</span></div></div><div className="poll"><div className="options">{pollChoices.map(([id,label],i)=><button className={vote===id?"on":""} onClick={()=>submitVote(id)} key={id}><small>0{i+1}</small><b>{label}</b><span>{vote===id?"TU VOTO":"VOTAR"}</span></button>)}<p aria-live="polite">{status||"Respuesta anónima · puedes cambiar tu voto"}</p></div><div className="results"><small>GRUPO DE AFINIDAD EN CONSTRUCCIÓN</small>{pollChoices.map(([id,label])=>{const pct=count?Math.round((results[id]||0)/count*100):0;return <div key={id}><span><b>{label}</b><em>{pct}%</em></span><i><b style={{width:`${pct}%`}}/></i></div>})}<p>Se actualiza automáticamente cada 3 segundos.</p></div></div></div></section>
  <section className="section" id="cierre"><div className="wrap"><Title n="04" title="La idea central" text="El método convierte incertidumbre en una conversación estructurada que permite prepararse antes de que el cambio ocurra."/><blockquote><small>NO BUSCAMOS ADIVINAR 2030</small><p>Buscamos ampliar las decisiones que podemos tomar <em>desde hoy.</em></p><span>Señales → afinidades → vectores → escenarios → estrategias</span></blockquote><div className="references"><h3>Referencia · APA 7</h3><p>Asociación Nacional de Facultades y Escuelas de Ingeniería. (2016). <i>Ingeniería industrial en México 2030: Escenarios de futuro. Estudio de planeación prospectiva</i>. ANFEI.</p><a href="https://www.anfei.mx/site/wp-content/uploads/2019/04/Libro_Ing_Industrial_2030.pdf" target="_blank" rel="noreferrer">Consultar publicación oficial ↗</a></div><footer><span>Universidad La Salle Bajío · Facultad de Ingenierías y Tecnologías · Equipo #2</span><span>19 de agosto de 2026</span></footer></div></section>
 </main>
}
function Title({n,title,text,inverse=false}:{n:string,title:string,text:string,inverse?:boolean}){return <div className={`title ${inverse?"inverse":""}`}><div><span>{n}</span><h2>{title}</h2></div><p>{text}</p></div>}
